<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<artifactId>customer-interaction-pl-ms</artifactId>
	<version>1.0.13-SNAPSHOT</version>
	<packaging>mule-application</packaging>
	<name>customer-interaction-pl-ms</name>
	<description>This a Process Layer application for Swiss Sense.</description>
	<groupId>628dd124-53a0-4efa-9453-7ee7109dfdf0</groupId>
	<parent>
		<groupId>nl.swisssense</groupId>
		<artifactId>parent-pom</artifactId>
		<version>1.0.0-SNAPSHOT</version>
		<relativePath>../parent-pom/parent-pom.xml</relativePath>
	</parent>
	<properties>
		<organisation.groupId>628dd124-53a0-4efa-9453-7ee7109dfdf0</organisation.groupId>
		<scm.repo>git@bitbucket.org:glosws/customer-interaction-pl-ms.git</scm.repo>
		<visualizer.displayName>Customer Interaction Process API</visualizer.displayName>
		<visualizer.layer>Process</visualizer.layer>
	</properties>
	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>false</filtering>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.mule.tools.maven</groupId>
				<artifactId>mule-maven-plugin</artifactId>
				<version>${mule.maven.plugin.version}</version>
				<extensions>true</extensions>
				<configuration>
					<cloudHubDeployment>
						<uri>https://eu1.anypoint.mulesoft.com/</uri>
						<muleVersion>${app.runtime}</muleVersion>
						<username>${username}</username>
						<password>${password}</password>
						<applicationName>${muleenv}-${project.artifactId}</applicationName>
						<environment>${chenv}</environment>
						<properties>
							<mule.ch.env>${muleenv}</mule.ch.env>
							<anypoint.platform.config.analytics.agent.enabled>true</anypoint.platform.config.analytics.agent.enabled>
							<anypoint.platform.analytics_base_uri>https://analytics-ingest.eu1.anypoint.mulesoft.com</anypoint.platform.analytics_base_uri>
							<anypoint.platform.base_uri>https://eu1.anypoint.mulesoft.com</anypoint.platform.base_uri>
							<anypoint.platform.client_id>${envclientid}</anypoint.platform.client_id>
							<anypoint.platform.client_secret>${envclientsecret}</anypoint.platform.client_secret>
							<customer-interaction-pl-ms-encryption-key>${customer-interaction-pl-ms-encryption-key}</customer-interaction-pl-ms-encryption-key>
							<anypoint.platform.visualizer.displayName>${visualizer.displayName}</anypoint.platform.visualizer.displayName>
							<anypoint.platform.visualizer.layer>${visualizer.layer}</anypoint.platform.visualizer.layer>
							<azure.clientid>${azure.clientid}</azure.clientid>
							<azure.clientsecret>${azure.clientsecret}</azure.clientsecret>
							<azure.vaultname>${azure.vaultname}</azure.vaultname>
							<azure.encryptkey>${azure.encryptkey}</azure.encryptkey>
							<azure.bypassflag>${azure.bypassflag}</azure.bypassflag>
							<azure.localfile>${azure.localfile}</azure.localfile>
						</properties>
						<workers>${workers}</workers>
						<workerType>${workertype}</workerType>
						<region>${workerregion}</region>
						<objectStoreV2>true</objectStoreV2>
						<businessGroup>Swiss Sense\Swiss Sense ICT</businessGroup>
						<deploymentTimeout>2000000</deploymentTimeout>
						<skipDeploymentVerification>${skipVerify}</skipDeploymentVerification>
					</cloudHubDeployment>
				</configuration>
				<executions>
					<execution>
						<id>deploy</id>
						<phase>deploy</phase>
						<goals>
							<goal>deploy</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>external.atlassian.jgitflow</groupId>
				<artifactId>jgitflow-maven-plugin</artifactId>
				<version>${jgitflow.maven.plugin.version}</version>
				<configuration>
					<pushReleases>true</pushReleases>
					<keepBranch>false</keepBranch>
					<localOnly>false</localOnly>
					<noTag>false</noTag>
					<noDeploy>false</noDeploy>
					<noReleaseMerge>false</noReleaseMerge>
					<squash>false</squash>
					<eol>native</eol>
					<allowUntracked>true</allowUntracked>
					<defaultOriginUrl>${scm.repo}</defaultOriginUrl>
					<enableSshAgent>true</enableSshAgent>
					<alwaysUpdateOrigin>true</alwaysUpdateOrigin>
					<pullDevelop>true</pullDevelop>
					<pullMaster>true</pullMaster>
					<allowSnapshots>true</allowSnapshots>
					<flowInitContext>
						<masterBranchName>master</masterBranchName>
						<developBranchName>develop</developBranchName>
					</flowInitContext>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-install-plugin</artifactId>
				<version>${maven.install.plugin.version}</version>
			</plugin>
			<plugin>
				<artifactId>maven-deploy-plugin</artifactId>
				<version>${maven.deploy.plugin.version}</version>
				<executions>
					<execution>
						<id>default-deploy</id>
						<phase>deploy</phase>
						<goals>
							<goal>deploy</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven.compiler.plugin.version}</version>
				<configuration>
					<compilerArgs>
						<args>-parameters</args>
					</compilerArgs>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>com.mulesoft.modules</groupId>
			<artifactId>mule-secure-configuration-property-module</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.modules</groupId>
			<artifactId>mule-apikit-module</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-http-connector</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>628dd124-53a0-4efa-9453-7ee7109dfdf0</groupId>
			<artifactId>json-logger</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>628dd124-53a0-4efa-9453-7ee7109dfdf0</groupId>
			<artifactId>azure-vault-custom-properties-provider-encrypted---connected-app</artifactId>
			<version>1.0.0</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.connectors</groupId>
			<artifactId>mule-azure-service-bus-connector</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>628dd124-53a0-4efa-9453-7ee7109dfdf0</groupId>
			<artifactId>customer-interaction-pl-ms</artifactId>
			<version>0.2.4</version>
			<classifier>raml</classifier>
			<type>zip</type>
		</dependency>
	</dependencies>
	<repositories>
		<repository>
			<id>anypoint-exchange-v3</id>
			<name>Anypoint Exchange V3</name>
			<url>https://maven.eu1.anypoint.mulesoft.com/api/v3/maven</url>
			<layout>default</layout>
		</repository>
	</repositories>
</project>