#%RAML 1.0 Trait

usage: |
   Deze library beschrijft wat de standaard technische fout responses zijn vanuit het Integratie Platform. Deze library moet daarom standaard worden ingevoegd in nieuw te bouwen REST services.

responses:
  400:
    description: Het bericht voldoet niet aan de eisen die in de service gesteld worden. In de error response wordt een hardcoded tekst teruggestuurd in combinatie met een beschrijving welk veld niet valide is.
    body:
      application/json:
        type: !include errorResponse.raml
        example: |
              {
              "error": "Message is invalid; [faultcode]"
              }
  401:
    description: Er wordt geen gebruik gemaakt van de valide authenticatie mogelijkheden zoals verkeerde login credentials
    body:
      application/json:
        type: !include errorResponse.raml
        example: |
              {
              "error": "You are not authenticated"
              }
  403:
    description: De aanvrager is geauthentiseerd maar niet geautoriseerd. Hiervoor moeten de juiste permissies worden aangevraagd bij de business owner.
    body: 
      application/json:
        type: !include errorResponse.raml
        example: |
          {
          "error": "You have no permission to this resource"
          }
  404:
    description: Het opgegeven pad of resource bestaat niet of kan niet worden gevonden.
    body:
      application/json:
        type: !include errorResponse.raml
        example: |
              {
              "error": "The requested resource could not be found. Your called URL is: [URL]"
              }
  405:
    description: De opgegeven methode is niet valide voor de opgevraagde resource.
    body:
      application/json:
        type: !include errorResponse.raml
        example: |
              {
              "error": "Method not allowed. The given method is as followed; [Method]"
              }
  413:
    description: Het verstuurde bericht is te groot om te verwerken. Het bericht moet voldoen aan de opgestelde eis van berichtgrootte.
    body:
      application/json:
        type: !include errorResponse.raml
        example: |
              {
              "error": "Message is too big. The size was '[payload size]' while '[acceptable size]' is acceptable"
              }
  422:
    description: Het verstuurde bericht is technisch goed verwerkt maar voldoet functioneel niet aan de eisen om verwerkt te worden.
    body:
      application/json:
        type: !include errorResponse.raml
        example: |
              {
              "error": "[functional error]"
              }
  500:
    description: De applicatie heeft het bericht niet succesvol kunnen verwerken door technische problemen.
    body:
      application/json:
        type: !include errorResponse.raml
        example: |
              {
              "error": "The service was not able to process the message correctly"
              }
  504:
    description: Het bericht kan niet worden verwerkt binnen de opgestelde timeout. 
    body: 
      application/json:
        type: !include errorResponse.raml
        example:  |
            {
            "error": "The server did not receive a response in time"
            }
