#%RAML 1.0 Library

usage: Voor elke systeem- en proceslaag moet Basic Authentication worden toegepast om gemakkelijker het berichtenverkeer te kunnen tracen tussen de verschillende componenten. 

securitySchemes:
    basicAuth:
      type: Basic Authentication